# Generated by Django 5.1.6 on 2025-02-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('nome_social', models.CharField(blank=True, max_length=255, null=True)),
                ('profissao', models.CharField(max_length=255)),
                ('endereco', models.TextField()),
                ('contato', models.CharField(max_length=50)),
            ],
        ),
    ]
